name: container # ワークフロー名を決定

# トリガーの設定
on:
    push: # プッシュ(マージ)が発生したときにトリガー
        branches:
            - develop

# 環境変数の設定
env:
    OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
    OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
    OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
    OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
    OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
    OCI_CLI_PASSPHRASE: ${{ secrets.OCI_CLI_PASSPHRASE }}

# ジョブの設定
jobs:
    filter-files: # 変更されたファイルを判定するジョブ
        name: Determine Changed Files
        runs-on: ubuntu-latest
        outputs:
            frontend: ${{ steps.filter.outputs.frontend }} # フロントエンドの変更時のフラグ
            backend: ${{ steps.filter.outputs.backend }} # バックエンドの変更時のフラグ
        steps:
            - name: Checkout repository # リポジトリをチェックアウト
              uses: actions/checkout@v4

            - name: Determine changed files # 変更されたファイルを判定
              id: filter
              uses: dorny/paths-filter@v3
              with:
                  filters: |
                      frontend:
                        - 'react/**/*.ts'
                        - 'react/**/*.tsx'
                        - 'react/Dockerfile'
                      backend:
                        - 'fastapi/**/*.py'
                        - 'fastapi/Dockerfile'

    frontend-build-and-push: # フロントエンドのビルドとプッシュを行うジョブ
        name: Frontend Build & Push
        needs: filter-files
        if: github.event_name == 'push' && needs.filter-files.outputs.frontend == 'true'
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository # リポジトリをチェックアウト
              uses: actions/checkout@v4

            - name: Docker build # Docker イメージをビルド
              run: docker build . --file react/Dockerfile --tag nrt.ocir.io/nrcmxxv7sjse/ec_service_test:nodejs-${{ github.sha }}

            - name: Login OCIR # OCIR にログイン
              uses: oracle-actions/login-ocir@v1.2.1
              with:
                auth_token: ${{ secrets.OCI_AUTH_TOKEN }}

            - name: Push container image # コンテナイメージを OCIR にプッシュ
              run: docker push nrt.ocir.io/nrcmxxv7sjse/ec_service_test:nodejs-${{ github.sha }}

    backend-build-and-push: # バックエンドのビルドとプッシュを行うジョブ
        name: Backend Build & Push
        needs: filter-files
        if: github.event_name == 'push' && needs.filter-files.outputs.backend == 'true'
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository # リポジトリをチェックアウト
              uses: actions/checkout@v4

            - name: Docker build # Docker イメージをビルド
              run: docker build . --file fastapi/Dockerfile --tag nrt.ocir.io/nrcmxxv7sjse/ec_service_test:python-${{ github.sha }}

            - name: Login OCIR # OCIR にログイン
              uses: oracle-actions/login-ocir@v1.2.1
              with:
                auth_token: ${{ secrets.OCI_AUTH_TOKEN }}

            - name: Push container image # コンテナイメージを OCIR にプッシュ
              run: docker push nrt.ocir.io/nrcmxxv7sjse/ec_service_test:python-${{ github.sha }}