name: Update manifest in external workflows

on:
    push:
        branches:
            - develop

jobs:
    update-manifest:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout this repo
              uses: actions/checkout@v4

            - name: Clone manifest repo
              run: |
                  git clone https://x-access-token:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/oimurat/dispatch-test.git
                  cd dispatch-test

            - name: Update manifest using yq
              run: |
                  cd dispatch-test
                  IMAGE_TAG="nrt.ocir.io/nrcmxxv7sjse/ec_service_test:nodejs-${{ github.sha }}"
                  yq eval ".deployment.template.frontendImageA = \"${IMAGE_TAG}\"" -i oke-test/values.yaml

            - name: Commit & Push
              run: |
                  cd dispatch-test
                  git config user.name "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git add -A
                  git commit -m "external-workflows: update manifest"
                  git push origin main

    frontend-lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Clone app repo
              run: |
                  git clone https://x-access-token:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/oimurat/lint-and-test-code.git
                  cd lint-and-test-code

            - name: Set up Node.js # Node.jsのセットアップ
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache-dependency-path: react/package-lock.json

            - name: clear npm cache # npmキャッシュのクリア
              run: |
                  cd lint-and-test-code/react
                  npm cache clean --force

            - name: Install dependencies # 依存関係のインストール
              run: |
                  cd lint-and-test-code/react
                  npm install

            - name: Run Prettier check # Prettierでコードフォーマットをチェック
              run: |
                  cd lint-and-test-code/react
                  npm run prettier -- --check .

            - name: Run ESLint #ESLintで静的解析を実施
              run: |
                  cd lint-and-test-code/react
                  npm run lint -- .